name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello world1"
      - name: Show env file
        cat /home/runner/work/bot31/bot31/.env
